### ISSUE TITLE
Some anime title is returning null

### ISSUE THREAD

**Issue by soruly** [AniList/ApiV2-GraphQL-Docs#10]
I've got a list of anime title that's returning null (total 461 null titles)
```
98476
98473
98474
98512
98576
98575
98761
98847
99084
99413
99424
99216
99425
99530
99646
99730
99731
99732
100246
100339
```
The title is fine on anilist and anilist APIv1
https://anilist.co/anime/100339/

[graphiql link](https://anilist.co/graphiql?query=%7B%0A%20%20Media(id%3A%20100339%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20id%0A%20%20%20%20title%20%7B%0A%20%20%20%20%20%20native%0A%20%20%20%20%20%20english%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Comment by Kazakuri** [comment]
It looks like the few I checked only have the romaji titles set for various reasons.
The migration guide from APIv1 to APIv2 should probably note that missing English and native titles will not have the romaji title filled in, if that's the intended behaviour.

Slightly unrelated, but the romaji title for id `100339` returns `Milpom★` but it's set to `MILPOM★` on AniList, which might not be intended either.

**Comment by joshstar** [comment]
Yeah this is intended behaviour for Api v2, [I've updated the migration docs with more info on this](https://anilist.gitbooks.io/anilist-apiv2-docs/migrating-from-apiv1.html). You don't have the `romaji` title field in your query and thats the only title language we currently guarantee to be non-null.

As for the capitalisation thing kaz mentioned that is also intended behaviour as by default we return the standardized capitalisation version of the titles unless the `stylised` argument is set to true or the user's preferred language is set to the stylised version.
