### ISSUE TITLE
Querying characters in media returns HTTP 500 when nested within another query

### ISSUE THREAD

**Issue by doongs** [AniList/ApiV2-GraphQL-Docs#104]
I have this query running on my site, and it has been working fine until today when I noticed that it now returns a HTTP 500 response. An internal API change may have led to this nested query breaking.

<pre><code>query ($id: Int) { 
    MediaListCollection(userId: $id, type: ANIME) {
      lists {
        name
        entries {
          media {
            id
            title {
              english
              romaji
            }
            characters(sort:FAVOURITES_DESC) {
              edges {
                node {
                  id
                  name{
                    full
                  }
                }
              }
            }
          }
          }
        }
      }
    }</code></pre>

![image](https://user-images.githubusercontent.com/61425162/99276825-10610380-27fb-11eb-9224-d591f53e00de.png)

Breaking out the query works fine, but I just wanted to point out this change

<pre><code>query($id: Int) {
  Media(id: $id) {
    title{
      romaji
      english
    }
    characters(sort:FAVOURITES_DESC, perPage: 25) {
            edges {
              node {
                id
                name{
                  full
                }
                image {
                  large
                }
                siteUrl
              }
              media {
                title {
                  romaji
                  english
                }
                id
                siteUrl
                coverImage {
                  extraLarge
                  large
                  medium
                  color
                }
              }
            }
          }
  }
}</code></pre>

**Comment by joshstar** [comment]
Hey sorry about this, fix should be live within the hour

**Comment by doongs** [comment]
Thanks, things seem to be working now!
