### ISSUE TITLE
AiringSchedule purged on 2-cour show while airing

### ISSUE THREAD

**Issue by ClawhammerLobotomy** [AniList/ApiV2-GraphQL-Docs#111]
It seems like the airingschedule was partially removed for a currently airing show between today and yesterday.

id: 114446
title: Higurashi no Naku Koro ni Gou

The airingSchedule now contains only episodes 14-24 rather than 1-24 as of earlier this week.

Is there a way to get the previous entries back?
Here is my query that I am using. 

```
{
  MediaListCollection(userId: 4257, type: ANIME, status: CURRENT, sort: STARTED_ON) {
    lists {
      entries {
        id
        media {
        id
        title {
          userPreferred
        }
        type
        seasonInt
        season
        seasonYear
        startDate {
          year
          month
          day
        }
        endDate {
          year
          month
          day
        }
        episodes
        duration
        nextAiringEpisode {
          airingAt
          episode
        }
        status
          airingSchedule {
          edges {
            node {
              airingAt
              episode
            }
          }
        },
        mediaListEntry {
          progress
        }
        }
        progress
      }
    }
  }
}
```

For more simplicity sake, all the extra info is removed from this example:

```
{
  MediaListCollection(userId: 4257, type: ANIME, status: CURRENT, sort: STARTED_ON) {
    lists {
      entries {
        id
        media {
        id
        title {
          userPreferred
        }
          airingSchedule {
          edges {
            node {
	      airingAt
              episode
            }
          }
        }
      }
    }
    }}}
```

**Comment by joshstar** [comment]
Sorry currently we can't ganruntee that past airing scheulde data will always be correct, we only attempt to ensure future airing dates are accurate. I'll make sure to make a note of this and add it to the docs.

At some point in the future we'll probably have "Episode" data which will contain more information about individual episodes and maintain accurate airing dates but thats a ways off for now.
