### ISSUE TITLE
Return media description asHtml

### ISSUE THREAD

**Issue by erengy** [AniList/ApiV2-GraphQL-Docs#12]
> Added missing asHtml arguments to remaining markdown fields.

This [example query](https://anilist.co/graphiql?query=query%20(%24id%3A%20Int)%20%7B%0A%20%20Media%20(id%3A%20%24id%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20id%0A%20%20%20%20title%20%7B%0A%20%20%20%20%20%20romaji%0A%20%20%20%20%7D%0A%20%20%20%20description(asHtml%3A%20true)%0A%20%20%7D%0A%7D&variables=%7B%22id%22%3A%201%7D) with `description(asHtml: true)` returns "Internal Server Error".

The query works without `asHtml`, but it returns a description with HTML tags (e.g. `<br>`).

> Those and the br tags are mainly a legacy thing though and I would like to go back and convert the descriptions to pure markdown with no html at some point in the near future

**Comment by joshstar** [comment]
Oops sorry, looks like I forgot to write a test for that one. 
Fix should be live now.
