### ISSUE TITLE
Staff.characterMedia.edges.characterRole value is misleading when the staff member voices multiple characters in the media

### ISSUE THREAD

**Issue by ben-hig** [AniList/ApiV2-GraphQL-Docs#121]
When a staff member voices multiple characters in one anime and they have different character roles, only one role is reflected by the `characterRole` value on the `characterMedia` `edge`s. Here is an example query:

{ Staff(id:95311) { staffMedia { edges { node { id } staffRole } } characterMedia { edges { characters { id } node { id } characterRole } } characters { edges { node { id } role } } }

And the results:
![image](https://user-images.githubusercontent.com/12514402/109360518-fea4e880-784c-11eb-99cf-331095362457.png)

As you can see, the character with ID 2587 has a Supporting role, but the `characterRole` value is "MAIN" because another character voiced by the same staff member in that anime has a role of "MAIN". 

This mistake is reflected on the staff's Anilist page as well:
![image](https://user-images.githubusercontent.com/12514402/109360752-5ba09e80-784d-11eb-8ae4-551d414fee65.png)
![image](https://user-images.githubusercontent.com/12514402/109360796-75da7c80-784d-11eb-8b14-6b4652eb5f99.png)

**Comment by joshstar** [comment]
Hey this should be fixed in an upcoming update (week or 2). Wasn't really a perfect way to fix it without making things super messy or breaking compatiabilty so media will basically be duplicated and the characters array will only contain the 1 character so the role is always correct.
