### ISSUE TITLE
MediaList filter by tag or tag_in as Media

### ISSUE THREAD

**Issue by matheusAle** [AniList/ApiV2-GraphQL-Docs#123]
query `MediaList` doesn't allow to filter by MediaTag. But Media query allows but don’t return all results.

**Comment by joshstar** [comment]
No plans on adding tag filtering to the MediaList query currently sorry.
To get all the results for the Media query you need to use Page query, see [here](https://anilist.gitbook.io/anilist-apiv2-docs/overview/graphql/pagination).
