### ISSUE TITLE
Edit watching list (Javascript)

### ISSUE THREAD

**Issue by diskxo** [AniList/ApiV2-GraphQL-Docs#134]
How can I add episodes to watching list with javascript when I logged into my account? 

now I have this code: 
![image](https://user-images.githubusercontent.com/64780086/122819315-93d75b80-d2da-11eb-957e-f32300a9527c.png)

**Comment by sachaw** [comment]
This is not a JavaScript specific question, see here https://anilist.gitbook.io/anilist-apiv2-docs/overview/graphql/mutations
PS use TS/es6 and above, will make your life easier

**Comment by diskxo** [comment]
yes, i think i will use typescript.

I would like to ask you something about the documentation: what is "new GuzzleHttp \ Client;" and how should I go about implementing it correctly in typescript? Thanks a lot: D, sorry for the ignorance, I'm new to programming

![image](https://user-images.githubusercontent.com/64780086/122832911-5ed40480-d2ec-11eb-8bbc-d6e8648251d5.png)

**Comment by sachaw** [comment]
That's PHP, not JavaScript.

Guzzle is an http client, alternatives for JS would be either Fetch, Axios or you could use a full graphql client like Apollo.

**Comment by diskxo** [comment]
Is this a good solution?
![immagine](https://user-images.githubusercontent.com/64780086/123037519-16e9d600-d3ef-11eb-9773-d9c9f7ebd942.png)

**Comment by sachaw** [comment]
Haven't run this, but it will be something along these lines, you will need to set your auth header.

```typescript
interface variables {
  id: number;
  mediaId: number;
  status:
    | "CURRENT"
    | "PLANNING"
    | "COMPLETED"
    | "DROPPED"
    | "PAUSED"
    | "REPEATING";
  progress: number;
}

const url = "https://graphql.anilist.co";

const query = `
mutation ($id: Int, $mediaId: Int, $status: MediaListStatus, $progress: Int){
    SaveMediaListEntry (id: $id, mediaId: $mediaId, status: $status progress: $progress) {
          id
          status
          progress
      }
  }
`;

const variables: variables = {
  id: 1,
  mediaId: 1,
  status: "CURRENT",
  progress: 1,
};

fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    query,
    variables,
  }),
})
  .then((res) => res.json())
  .then((result) => console.log(result));

```

**Comment by diskxo** [comment]
I have this problem with your code:
![immagine](https://user-images.githubusercontent.com/64780086/123546345-81d33e00-d75c-11eb-9d55-6fa3a150d6c5.png)

what is it due to?

**Comment by diskxo** [comment]
![immagine](https://user-images.githubusercontent.com/64780086/123547892-df6a8900-d762-11eb-853c-921b7918e18a.png)
how should i create the header? I have tried this, but I get this error:

![immagine](https://user-images.githubusercontent.com/64780086/123547924-04f79280-d763-11eb-879a-9ccd66c3f543.png)

**Comment by sachaw** [comment]
log the full response, under the validation object (`errors` > `validation`) it will have the reason i.e:

```json
"validation": {
    "id": [
        "The selected id is invalid."
    ]
}
```

**Comment by diskxo** [comment]
How can i get the full reason in the console? The error message is only this one:
```
{
  errors: [
    {
      message: 'validation',
      status: 400,
      locations: [Array],
      validation: [Object]
    }
  ],
  data: { SaveMediaListEntry: null }
}
```

**Comment by sachaw** [comment]
Use
'''typescript
console.log(result.errors.location)
'''

**Comment by sachaw** [comment]
@diskxo have you solved this, if so please close this issue

**Comment by diskxo** [comment]
no, I am having trouble finding the error despite your advice. I get "undefined" as output

![immagine](https://user-images.githubusercontent.com/64780086/124616628-8a232b80-de76-11eb-8a88-35b368192cf2.png)

**Comment by matchai** [comment]
It doesn't seem like the issues you're running into are specific to AniList's API. I'd recommend heading to StackOverflow for help troubleshooting requests in JavaScript. 😊 

I'll be closing this issue, but feel free to reopen it if you are running into bugs with the AniList API.

**Comment by sachaw** [comment]
@diskxo feel free to dm me on discord sachaw#5079 if you want help.

**Comment by diskxo** [comment]
Ok, thanks
