### ISSUE TITLE
Notifications query returning a 500 error

### ISSUE THREAD

**Issue by bvalyan** [AniList/ApiV2-GraphQL-Docs#14]
I'm trying to fetch all notifications but my query is just giving me a 500 error. It was working before, but now it's not.

This query can be found here:

https://pastebin.com/Yza0C1RT

Thanks!

**Comment by joshstar** [comment]
Looks like the error is coming from `(resetNotificationCount: false)`, I'll fix this as soon as I can but in the mean time you can remove that bit as false is the default value for resetNotificationCount.

**Comment by bvalyan** [comment]
Sounds good, thanks!

**Comment by bvalyan** [comment]
Side note/ update to this. I started getting the error even when not including the resetnotificationcount. When I took out "createdAt" as a return value, I started getting good responses.

**Comment by joshstar** [comment]
Ah thanks, fix for both issues is now live 😄
