### ISSUE TITLE
How can I set a filter Argument with 2 values or more?

### ISSUE THREAD

**Issue by kuchienkz** [AniList/ApiV2-GraphQL-Docs#15]
Say I want to get list of media with status: "RELEASING" or "FINISHED". Something like:
```{
  Page (page:1 perPage:50){
    media (status: {FINISHED, RELEASING} sort: POPULARITY_DESC type: ANIME startDate_greater: 20170000){
      type
      id
      averageScore
      title {
        romaji
      }
    }
  }
}
```
What is the correct syntax? I'm very new to graphQL :D

**Comment by joshstar** [comment]
Currently status only accepts a single value, tho I'll add the extended _in argument for it after Christmas. 

For fields that do accept multiple values you would use the array syntax like `[value1, value2]`, so once status_in its added it will be `status_in: [FINISHED, RELEASING]`.

**Comment by kuchienkz** [comment]
I will wait :D

**Comment by joshstar** [comment]
I'll keep this open until the feature is implemented

**Comment by joshstar** [comment]
This is now live 😄

**Comment by kuchienkz** [comment]
Yay~
