### ISSUE TITLE
I need help with access tokens

### ISSUE THREAD

**Issue by josephyhu** [AniList/ApiV2-GraphQL-Docs#152]
I want the user to be able to paste the access token directly to an input field instead of pasting it manually to `accessToken` variable in the JavaScript file. How do I do that? Here are relevant codes:

**index.html**
```html
<div id="login">
    <a href="https://anilist.co/api/v2/oauth/authorize?client_id=6814&response_type=token" target="_blank">Login with AniList</a>
    <form>
        <label for="tokenInput">Enter the access token provided here<span class="required">*</span></label>
        <input type="text" id="tokenInput" required>
        <button type="submit" id="btnToken">Authenticate</button>
    </form>
</div>
```

**script.js**
```javascript
// Todo
btnToken.addEventListener('click', e => {
    e.preventDefault();
    accessToken = document.querySelector('#tokenInput').value;
});

let getAuthenticatedUserQuery = `
query {
Viewer {
    id
}
}`

fetch(url, {
    method: 'POST',
    headers: {
        "authorization": "Bearer " + accessToken,
        "Content-Type": "application/json",
        "Accept": "application/json"
    },
    body: JSON.stringify({
        query: getAuthenticatedUserQuery
    }),
})
    .then(checkAuthenticatedStatus)
    .then(res => res.json())
    .then(data => userId = data.data.Viewer.id)
    .catch(err => console.error('You have to be authenticated to use this app.', err))

function checkAuthenticatedStatus(res) {
    if (res.ok) {
        login.innerHTML = '';
        return Promise.resolve(res);
    } else {
        loggedIn.innerHTML = '';
        return Promise.reject(new Error(res.statusText));
    }
}
```

**Comment by josephyhu** [comment]
Also how do I verify the access token? It works if the fetch and the status checking function is outside the event handler (i.e. the appropriate html elements get hidden depending on whether accessToken is valid or not), but it doesn't work if they are inside the handler.

**Comment by sachaw** [comment]
It's completely up to you how you implement the auth.
Here's a reference implementation that I wrote:
https://github.com/scrobble-moe/server/blob/master/src/models/linkedAccountResolver.ts

**Comment by josephyhu** [comment]
I'm not sure how to do it though. If I do a click event listener and set `accessToken` to whatever user types in the input field, it doesn't save the value to the `accessToken` outside the listener even though (I thought) `accessToken` should be a global variable. Also putting all the code (in the snippet) inside the listener doesn't work either since the section with id `loggeddIn` no longer gets hidden and even though I can get authenticated that way I lose my authentication whenever I refresh the page.

**Comment by sachaw** [comment]
I'd get started with a framework like react or Vue and get the hang of working with browser side js, it will help you get the skills to do this.
