### ISSUE TITLE
failed to fetch response

### ISSUE THREAD

**Issue by dev-aly3n** [AniList/ApiV2-GraphQL-Docs#156]
I keep getting this error everywhere. what is wrong?
![image](https://user-images.githubusercontent.com/79654879/148703267-dd3f11b8-73aa-4480-8396-b48ddfa8d19b.png)

**Comment by allanrivers** [comment]
![image](https://user-images.githubusercontent.com/50601215/148704624-eda124e0-a55b-4c96-812c-8bc57144f52e.png)
