### ISSUE TITLE
Conditionally display login link.

### ISSUE THREAD

**Issue by josephyhu** [AniList/ApiV2-GraphQL-Docs#163]
(index.php)
```
<?php
require_once 'inc/functions.php'; 
$query = [
    'client_id' => '7672',
    'redirect_uri' => 'http://localhost/jys-aniapp-v2', // http://example.com/callback
    'response_type' => 'code'    
];


$url = 'https://anilist.co/api/v2/oauth/authorize?' . urldecode(http_build_query($query));

require_once 'inc/header.php';
?>
<main>
<?php
if (!isset($code)) {
    echo "<a href='$url'>Login with Anilist</a>";
}
$code = $_GET['code'];
$id = get_id();
echo $id;
?>
</main>
<?php require_once 'inc/footer.php'; ?>
```

I'm trying to display the login link only if `$code` is not set; however, it keeps displaying even after `$code` has been set. What's wrong with my code? I know I have been correctly logged in because my app is listed on the App & Automail Settings page.

**Comment by josephyhu** [comment]
Looks like I've fixed it.

**Comment by sachaw** [comment]
This isn't the place to ask for help with your specific projects unless it is directly related to AniList itself.
