### ISSUE TITLE
API Terms of Use Question

### ISSUE THREAD

**Issue by majora2007** [AniList/ApiV2-GraphQL-Docs#167]
Hello,

I am planning on building a metadata service (private, non-commercial) for the service [Kavita](https://github.com/Kareadita/Kavita), which is a reading self-hosted service (OSS). In the terms of conditions, there is a mention of:

> ‘Hoarding’ or mass collection of data from the AniList API is strictly prohibited.

I'm trying to understand what the exactly means? Does this mean I cannot cache content for long periods of time? Can anyone give me some advice on this.

My current plan of action is to aggregate different data from difference sources, AniList, MAL, etc into my own DB structure and keep it myself. But if this is rule breaking, I can avoid using AniList itself or build a different mechanism to reduce caching.

**Comment by matchai** [comment]
The spirit of the requirement is to prohibit scraping our entire database. Caching specific data for long periods of time is fine, but if you are building a replica of all our data as part of your cache, we're a little less onboard.

**Comment by majora2007** [comment]
Okay, then I think it should be fine. I'm not trying to build a replica, I'm trying to merge data between AniList and MAL to provide metadata to user's manga collections via a private api, non-commercialized. Of course, records still need to be updated after some amount of time. I'm just trying to avoid hammering your servers and also be able to provide some normalization between different metadata hooks. 

Once I get further into development, I'll circle back with you to ensure there is no problems. Appreciate the speedy response.
