### ISSUE TITLE
Option to return MediaList.customLists as Array of Tuples

### ISSUE THREAD

**Issue by danejur** [AniList/ApiV2-GraphQL-Docs#17]
Right now, querying MediaList's customLists returns a JSON structure containing a number of key/value properties, namely "custom list name" (string) and "presence on said list" (bool).

`"customLists": {
              "List One": false,
              "List Two": true
            }`

This is somewhat difficult to parse into a typed language, as the number and name of properties is dynamic and unavailable before runtime. (There are ways to get around this, but I'd like to keep those as "last resort" options).

Would it be possible to pass an option to the query to allow for the customLists property to be returned as a collection of Tuples instead? e.g.

`"customLists": [
              { "List One": false },
              { "List Two": true } ]`

**Comment by joshstar** [comment]
I think this should be okay since customLists returns a JSON data type, if it returned a proper graphql type then it wouldn't be possible to change its structure. 

I do wounder if a structure like this would be better? Just removing the keys all together 
```
"customLists": [ 
    { 
        "name": "List One",
        "enabled": false,
    },
    { 
        "name": "List Two",
        "enabled": true,
    },
]
```

**Comment by danejur** [comment]
Either way would be fine with me. Whatever is easiest to maintain for you guys!

**Comment by joshstar** [comment]
This is now live, you can use the `asArray` boolean argument on the customLists field to get it. 
Docs should be updated in graphiql sidebar already and I'll update our graphql reference docs shortly.

**Comment by danejur** [comment]
Thanks, @joshstar !
