### ISSUE TITLE
Field clarity issue

### ISSUE THREAD

**Issue by God-Dead** [AniList/ApiV2-GraphQL-Docs#174]
when I was using the graphiQL it told me to use the field statistics but that field does not exits.
![error](https://user-images.githubusercontent.com/82600273/182836499-ad3a9ccf-943c-4980-9721-faaeab5e70d2.PNG)

**Comment by M0rimasa** [comment]
It doesn't exist because you're querying it on the root schema not the user object as you put it outside it.
![firefox_2022-08-05_22-32-00](https://user-images.githubusercontent.com/21118850/183158440-885bed5b-ece6-4832-b656-435bfa31c4d6.png)
