### ISSUE TITLE
Querying by Title

### ISSUE THREAD

**Issue by Pelps12** [AniList/ApiV2-GraphQL-Docs#180]
Is there a way to query the AniList GQl API by the title rather than the id.

**Comment by segfault0x61** [comment]
It should be the same as doing it by id, just use a the title with type String in-place.

```graphql
query ($title: String) {
  Media (search: $title, type: ANIME) {
    id
    title {
      romaji
      english
      native
    }
    status
    description
    episodes
    averageScore
  }
}
```

**Comment by Pelps12** [comment]
Thank you. I'm not too experienced with GrpahQL
