### ISSUE TITLE
Media search not functioning as expected

### ISSUE THREAD

**Issue by danejur** [AniList/ApiV2-GraphQL-Docs#19]
When I execute the following query:
`
query ($query: String, $type: MediaType) {
  Page {
    pageInfo {
      total
    }
    media(search: $query, type: $type) {
      id
    }
  }
}
`
with the attached variables of: `{
  "query": "shoujo",
  "type": "MANGA"
}`
the response is as follows: `
{
  "data": {
    "Page": {
      "pageInfo": {
        "total": 0
      },
      "media": []
    }
  }
}`

A quick look over at AniList's APIv1 search shows that there are definitely more than 0 manga with a title containing the term "shoujo". When executing the query again, this time dropping the variable parameter of "query" completely, the response is more appropriate, showing a total of roughly 39k records found.

Playing around with the queries a bit more shows that this isn't exclusive to manga searches, either. Searching for anime with the term "ai" returns a page response showing a total of 50 records, but once again, v1 tells a very different story.

**Comment by joshstar** [comment]
Fix should now be live.
