### ISSUE TITLE
Pre-Release Discussion

### ISSUE THREAD

**Issue by joshstar** [AniList/ApiV2-GraphQL-Docs#2]
AniList Api v2 is now in pre-release 🎉 

While you can expect some breaking changes this is a great time to start testing out the Api or thinking about how to migrate from v1.

Most of the Api has been documented but there is still a fair bit to doc. Theres also a few features that I haven't yet completed but v2 is mostly feature complete already.

I'm really interested in finding any of the following issues and getting them fixed before we make a stable release and can no longer make breaking changes. So if you find any of these or any other issues please do say here.
- Bugs
- Inconsistent naming (Fields, Queries, Mutations, Objects etc)
- Inconsistent typing or data responses
- Anything available in Api v1 not available in v2.

Here is my current list of things to fix before stable but I'm sure theres somethings I've missed:
- Add User & Media stats types
- Add User options mutation
- Add Media Tag mutations

Docs:
- The main Api Documentation is [here](https://joshstar.gitbooks.io/anilist-apiv2-docs/graphql.html), and will give you a basic run down of how the Api works.
- The API Reference Docs are [here](https://anilist.github.io/ApiV2-GraphQL-Docs/) and include every query, mutation, field, type etc with documentation (mostly) .
- The GraphiQL interactive Api editor is [here](https://anilist.co/graphiql) and lets you easily test writing your own queries. You do need to be logged into AniList to use this, and mutations are not currently available there. The side bar on the right displays the same information as the reference docs.

V2 is definitely a lot more verbose than v1 but it offers so much more flexibility and consistency that I hope you all find the extra bit of typing worth it in the end.

If you have any questions or want some help feel free to leave that as a reply here or you can message me on the AniList discord #programming channel.

**Comment by danejur** [comment]
Just to have a good timetable: Do you have any idea about the end of life date for v1 of the API?

**Comment by joshstar** [comment]
Once Api v2 is stable Api v1 will be considered deprecated and 6 months after that Api v1 will be shutdown. However I do need to migrate the entire front of the AniList website over to v2 so we may need to delay the shutdown by a few months but we'll see closer the time.

**Comment by joshstar** [comment]
Search should be all fixed now. 
A note for migration, v1 anime/manga search sorted by popularity secondary to the search relevance, so if you want to duplicate the exact result set you got from v1 search add the sort: popularity argument.

**Comment by ricklancee** [comment]
side note: Props to the v2 API. GraphQL is awesome and having an anime api with based on a graph is even more awesome, so 👍  

The thing i find a bit weird is that the boolean on the PageInfo Type is called `hastNextPage` instead of `hasNextPage`. Is this a typo?

**Comment by joshstar** [comment]
Ha yeah that is definitely a typo, thanks, will fix.

**Comment by ratan12** [comment]
After some tests it looks very promising. I am middle in rewriting some Atarashii parts and this could be a big benefit.

**Comment by ricklancee** [comment]
The interactive editor is unaccessible. It's throwing the error `{"error":{"status":401,"messages":["Unauthorised"]}}`. The api itself seems to be working fine. 

https://anilist.co/graphiql

**Comment by ricklancee** [comment]
Possible Bug:

Some `genres` fields the Media types return empty strings in the array. For instance the Media "Koi to Uso" (id: `98320`) contains 4 empty strings in the genres array.

```
// Api response
genres: ["Drama", "Romance", "", "", "", ""]
```

Could these empty strings be filtered out? Currently i'm filtering these in my apps but it would be nice if the api does this.

**Comment by joshstar** [comment]
You need to be logged into AniList to use graphiql at the moment. And yeah will get those genres fixed.

**Comment by cylonu87** [comment]
Is it a bug ?

I tried to update the score of an anime in my library. 
If I send this
`{"query":"mutation { SaveMediaListEntry(id:17356456, scoreRaw:30) {id}}", "variables":null}` or `{"query":"mutation { SaveMediaListEntry(id:17356456, mediaId:21, scoreRaw:30) {id}}", "variables":null}`, the server return "500 Internal Server Error". 

So I tried to replace it by 
`{"query":"mutation { UpdateMediaListEntries(ids:[17356456], scoreRaw:30) {id}}", "variables":null}` and it's working.

**Comment by cylonu87** [comment]
I have another problem. I'm trying to update the number of episodes watched like this:
`{"query":"mutation {   UpdateMediaListEntries(ids:[15975603], progress:100) {    id, progress   }}", "variables":null}`

If the value of progress is between 0 and 100, there is no problem. If progress > 100 (the series has 500 episodes), the server return an error 400.

**Comment by cylonu87** [comment]
I'm trying to update startedAt and completedAt of an entry:

This query update the status but the startedAt is not updated (the field Start Date is empty on the website):
`{"query":"mutation {   UpdateMediaListEntries(ids:[17361681], status:CURRENT , startedAt:{year:2017, month:8, day:16}  ) {    id, progress   }}", "variables":null}`

When I update the completedAt:
`{"query":"mutation {   UpdateMediaListEntries(ids:[17361681], status:COMPLETED  , completedAt:{year:2017, month:8, day:16} ) {    id, progress   }}", "variables":null}` 
the server return a 400 error with this message:
`{"data":{"UpdateMediaListEntries":null},"errors":[{"message":"Undefined variable: date","status":400,"locations":[{"line":1,"column":14}]}]}`

**Comment by joshstar** [comment]
@cylonu87 thanks for letting me know, I'll get all those fixed later this week when I get back home.

**Comment by ricklancee** [comment]
Found a typo in the API reference docs about the Enum MediaSeason: `Spring: Months March to Spring` should probably be `Spring: Months March to May`. 

https://anilist.github.io/ApiV2-GraphQL-Docs/mediaseason.doc.html

**Comment by cylonu87** [comment]
There are duplicates when searching the list of characters:
```
{
  Media(id: 20, type: ANIME) {
    characters(sort: ROLE) {
      edges {
        node {
          id
          name {first, last}
        }
      }
    }
  }
}
```

In the result, Sasuke Uchiha is returned 7 times.
```
{
  "data": {
    "Media": {
      "characters": {
        "edges": [
          {
            "node": {
              "id": 17,
              "name": {
                "first": "Naruto",
                "last": "Uzumaki"
              }
            }
          },
          {
            "node": {
              "id": 13,
              "name": {
                "first": "Sasuke",
                "last": "Uchiha"
              }
            }
          },
          {
            "node": {
              "id": 85,
              "name": {
                "first": "Kakashi",
                "last": "Hatake"
              }
            }
          },
          {
            "node": {
              "id": 13,
              "name": {
                "first": "Sasuke",
                "last": "Uchiha"
              }
            }
          },
          {
            "node": {
              "id": 145,
              "name": {
                "first": "Sakura",
                "last": "Haruno"
              }
            }
          },
          {
            "node": {
              "id": 145,
              "name": {
                "first": "Sakura",
                "last": "Haruno"
              }
            }
          },
          {
            "node": {
              "id": 85,
              "name": {
                "first": "Kakashi",
                "last": "Hatake"
              }
            }
          },
          {
            "node": {
              "id": 17,
              "name": {
                "first": "Naruto",
                "last": "Uzumaki"
              }
            }
          },
          {
            "node": {
              "id": 17,
              "name": {
                "first": "Naruto",
                "last": "Uzumaki"
              }
            }
          },
          {
            "node": {
              "id": 145,
              "name": {
                "first": "Sakura",
                "last": "Haruno"
              }
            }
          },
          {
            "node": {
              "id": 85,
              "name": {
                "first": "Kakashi",
                "last": "Hatake"
              }
            }
          },
          {
            "node": {
              "id": 17,
              "name": {
                "first": "Naruto",
                "last": "Uzumaki"
              }
            }
          },
          {
            "node": {
              "id": 13,
              "name": {
                "first": "Sasuke",
                "last": "Uchiha"
              }
            }
          },
          {
            "node": {
              "id": 145,
              "name": {
                "first": "Sakura",
                "last": "Haruno"
              }
            }
          },
          {
            "node": {
              "id": 85,
              "name": {
                "first": "Kakashi",
                "last": "Hatake"
              }
            }
          },
          {
            "node": {
              "id": 17,
              "name": {
                "first": "Naruto",
                "last": "Uzumaki"
              }
            }
          },
          {
            "node": {
              "id": 17,
              "name": {
                "first": "Naruto",
                "last": "Uzumaki"
              }
            }
          },
          {
            "node": {
              "id": 13,
              "name": {
                "first": "Sasuke",
                "last": "Uchiha"
              }
            }
          },
          {
            "node": {
              "id": 145,
              "name": {
                "first": "Sakura",
                "last": "Haruno"
              }
            }
          },
          {
            "node": {
              "id": 13,
              "name": {
                "first": "Sasuke",
                "last": "Uchiha"
              }
            }
          },
          {
            "node": {
              "id": 17,
              "name": {
                "first": "Naruto",
                "last": "Uzumaki"
              }
            }
          },
          {
            "node": {
              "id": 13,
              "name": {
                "first": "Sasuke",
                "last": "Uchiha"
              }
            }
          },
          {
            "node": {
              "id": 13,
              "name": {
                "first": "Sasuke",
                "last": "Uchiha"
              }
            }
          },
          {
            "node": {
              "id": 85,
              "name": {
                "first": "Kakashi",
                "last": "Hatake"
              }
            }
          },
          {
            "node": {
              "id": 145,
              "name": {
                "first": "Sakura",
                "last": "Haruno"
              }
            }
          }
        ]
      }
    }
  }
}
```

**Comment by cylonu87** [comment]
I tried to update the rewatched value with this query:
`{"query":"mutation { UpdateMediaListEntries(ids:[17361681], repeat:2) {id}}", "variables":null}`.
The server is returning this error:
`{"data":null,"errors":[{"message":"Unknown argument \"repeat\" on field \"UpdateMediaListEntries\" of type \"Mutation\".","status":400,"locations":[{"line":1,"column":51}]}]}`.

I can read the "repeat" field when using `MediaListCollection {statusLists {}}`, but it seems missing for `SaveMediaListEntry `and `UpdateMediaListEntries`.

**Comment by joshstar** [comment]
Thanks to everyone for reporting issues here and on the discord, the following changes should now be live: 

- Fixed genres array having empty strings
- Fixed null media titles being returned as empty strings
- Fixed season field sometimes causing a 500 error
- Fixed duplicate characters in media characters connection (when a character had multiple voice actors)
- Fixed SaveMediaListEntry mutation returning 500 error
- Added missing repeat argument to MediaList mutations 
- Removed maximum value validation from MediaList progress and volumeProgress arguments
- Fixed MediaList startedAt & completedAt arguments throwing an error
- Added userName argument to media list queries
- Fixed anime/manga specific fields (episodes, chapters etc) returning non-null values for the opposite media types
- Fixed spelling mistake in PageInfo field hasNextPage (was hastNextPage)
- Fixed incorrect description in the Spring season enum description

**Comment by soruly** [comment]
@joshstar 
How would you implement Rate Limiting? per IP or per client ID? or per access_token?

**Comment by joshstar** [comment]
At the moment rate limiting is done by IP. Tho I can understand that might be an issue for server side apps/bots so I'll probably add some kind of approval process to raise the rate limit for a specific IP.

**Comment by cylonu87** [comment]
@joshstar Thank you for fixing the bugs, I tested the bugs I reported and they are fixed except this one:
`{"query":"mutation {SaveMediaListEntry(id:17369712, completedAt:{year:2017, month:8, day:21}) {id}}", "variables":null}` 
cause this error: 
`{"data":{"SaveMediaListEntry":null},"errors":[{"message":"Undefined variable: date","status":400,"locations":[{"line":1,"column":11}]}]}`

startedAt works (checked on the website).

**Comment by joshstar** [comment]
@cylonu87 Thanks again, fix for that is now live.

**Comment by joshstar** [comment]
Crunchyroll episode links & data are now available via the streamingEpisodes field on the Media type. 
I don't want to risk spamming crunchyroll a few thousand times in a couple hours so I'm staggering the initial data creation over the next week.

**Comment by bvalyan** [comment]
Quick question @joshstar. I'm using Oauth, successfully, but is there a way to return the user ID when the access token is acquired? I'd like to be able to use it to run queries for the user's info once they have signed in without them having to enter their name if that makes sense.

**Comment by Kazakuri** [comment]
Yeah, there's a `Viewer` query that returns the currently authenticated user

```graphql
query {
  Viewer {
    id 
  }
}
```

But if you only care about the user's ID, APIv2 access tokens are JWT so you can also just look at the `sub` field of the JWT payload. 

For example in JavaScript it could look something like this:

```javascript
const payload = JSON.parse(atob(accessToken.split('.')[1]));
const userId = payload.sub;
```

**Comment by bvalyan** [comment]
Oh that's perfect! Must've missed that. thanks!

**Comment by bvalyan** [comment]
Hey, not sure if you're aware, getting 500 internal server errors on my requests now. Specifically when querying media. I noticed it start happening last night.

**Comment by joshstar** [comment]
@bvalyan Ah sorry about that, I updated some package dependencies so its probably related to that. 
Can you give me some examples of queries not working as I can't seem to find any

**Comment by bvalyan** [comment]
Sure, this was the query I was trying to run earlier I believe. Irma has taken my power though so I'm trying to do this from a phone.

query individualAnime($id: Int!){
                Media(isAdult: false, type: ANIME, id: $id ) {
                  id
                  isFavourite
                  episodes
                  externalLinks {
                        url
                      }
                  startDate {
                    day
                    month
                    year
                  }
                  endDate {
                    day
                    month
                    year
                  }
                  title {
                    english
                    romaji
                  }
                  coverImage {
                    large
                  }
                  genres
                  popularity
                  description
                  format
                  averageScore
                        relations{
                          nodes{
                             id
                        episodes
                        startDate {
                          day
                          month
                          year
                        }
                        endDate {
                          day
                          month
                          year
                        }
                        title {
                          english
                          romaji
                        }
                        coverImage {
                          large
                        }
                        genres
                        popularity
                        description
                        format
                        averageScore
                        status
                          }
                        }
                    }
              }

**Comment by joshstar** [comment]
@bvalyan Thanks for the help, should be fixed now :) 
Hope everythings alright there and your power comes back soon

**Comment by bvalyan** [comment]
Thanks! Still no power but my app's back online. Thanks for the quick fix.

**Comment by leonekmi** [comment]
```javascript
var query = `
mutation ($mediaId: Int, $progress : Int, $MediaListStatus: MediaListStatus) {SaveMediaListEntry (mediaId: $mediaId, progress: $progress, status: $MediaListStatus) { id progress status }}
`;
var variables = {
    mediaId: animeId,
    progress: episode,
    status: "CURRENT"
};
```

Fetching this changes the progress but not the status :/

**Comment by joshstar** [comment]
@leonekmi your status variable is called `status` in the your variables object but referenced as `MediaListStatus` in the mutation string.

**Comment by leonekmi** [comment]
aaaaaaahhhhh,yes ^^

**Comment by bvalyan** [comment]
If anyone has a moment, would you mind giving me a quick example of retrieving Activity data from the union structure? I've been looking it up online but I'm having no luck with the Graphql editor.

**Comment by Kazakuri** [comment]
```graphql
query {
  Activity(id: 9105245) {
    ... on TextActivity {
      text
    }
    ... on ListActivity {
      media {
        title {
          userPreferred
        }
      }
    }
    ... on MessageActivity {
      message
    }
  }
}
```

**Comment by bvalyan** [comment]
Oohhhh, so the ellipses are actually part of the syntax. Haha ok, thanks!

**Comment by bvalyan** [comment]
Hey, quick question, did anything change recently? I run a query to get a feed of ListActivities for users and the people they follow. Normally this returns all my activities and the activities of those I follow. However, I was using my app last night and all my activities were gone and I could only see the activities of the users I'd followed.

This is the query I use for it:
[query](https://pastebin.com/tBijC299)

Before
![22054500_10155555996097860_565951777_n](https://user-images.githubusercontent.com/10552972/31058138-c6e2c288-a6bc-11e7-91b9-1b31e09461fd.png)

Now
![screenshot_1506886450](https://user-images.githubusercontent.com/10552972/31058217-03ff1076-a6be-11e7-92bf-97fc567b3825.png)

**Comment by joshstar** [comment]
@bvalyan Hmm nothings change on our end so not sure really, the query still includes my user when using isFollowing so seems to be working for me. 

You are viewing the oldest items at the moment, you can add sort: ID_DESC to the activities field query to get newest first and see if it works then?

**Comment by bvalyan** [comment]
For sure, after looking at it a bit more I think it’s some weirdness with new pages. I’ll give that a shot!

**Comment by joshstar** [comment]
New update it now live, this should hopefully be the last before we go stable next month. Its been quite awhile since the last update so a fair amount has changed, including some breaking changes.

Media
- Removed Doujin, Manhua, & Manhwa from MediaFormatEnum [Breaking]
- Added isLicensed field. (Replacement for Doujin format)
- Added countryOfOrigin field (Replacement for Manhua, & Manhwa formats)
- Removed youtubeId field [Breaking]
- Added trailer field & MediaTrailer object type (Replacement for youtubeId)
- Added averageScore & popularity arguments to media query
- Added media stats

MediaList
- Collection - Split completed list sections are now included in the status lists, instead of custom lists objects [Breaking]

Activity
- Changed the field users (Array) to user (object) [Breaking]
- Removed groupActivity query argument [Breaking] (The functionality for this was never implemented)

User
- Added initial user stats
- The field unreadNotificationCount now only return the count for the authenticated user

Misc
- Raised rate limit from 60 to 90 requests per minute
- Added functionality to enable manual raise of rate limit - [Details](https://anilist.gitbooks.io/anilist-apiv2-docs/rate-limiting.html)
- Added functionality to replicate Api v1's Auth Pin grant type - [Details](https://anilist.gitbooks.io/anilist-apiv2-docs/oauth.html)
- A few of minor bug fixes for media, characters, staff, activity, and media lists
- Added missing isFavourite field for character, staff, & studio types
- The following queries now require at least 1 argument: Media, MediaList, User, AiringSchedule, Character, Staff, Studio, Review, Activity, ActivityReply, Thread, ThreadComment [Breaking] (Note: this does not apply to the Page field versions)

**Comment by joshstar** [comment]
[The initial migration queries are up](https://github.com/AniList/ApiV2-GraphQL-Docs/tree/master/migration), these aim to replicate the REST routes of Api v1 as closely as possible. 

As said in the read-me, Its recommended you don't use theses queries as-is. Instead, modify them for what you need, remove fields you aren't going to use, add fields/arguments you require, and merge queries together where appropriate.

A few other minor changes and bug fixes just went live too:
- Added missing bannerImage field to UserType.
- Added mediaId argument to Activity query.
- Fixed messageActivity notification type causing a 500 error.
- The field context on the AiringNotificationType has been renamed to contexts to avoid type conflicts with other notification types. [Breaking]
- The followings field on the PageType has been renamed to following. [Breaking]
- Removed accidental search argument from Review query. [Breaking]

**Comment by zr00130** [comment]
so I noticed when filtering character role type MAIN it's returning both MAIN and SUPPORTING results

```graphql
{
  Media(id: 1, type: ANIME) {
    id
    title {
      userPreferred
    }
    characters(role: MAIN) {
      edges {
        role
        node {
          name {
            first
            last
          }
        }
        voiceActors(language: JAPANESE) {
          name {
            first
            last
          }
          language
        }
      }
    }
  }
}
```

[results in graphiql](https://anilist.co/graphiql?query=%7B%0A%20%20Media(id%3A%201%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20id%0A%20%20%20%20title%20%7B%0A%20%20%20%20%20%20userPreferred%0A%20%20%20%20%7D%0A%20%20%20%20characters(role%3A%20MAIN)%20%7B%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20role%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20first%0A%20%20%20%20%20%20%20%20%20%20%20%20last%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20voiceActors(language%3A%20JAPANESE)%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20first%0A%20%20%20%20%20%20%20%20%20%20%20%20last%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20language%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Comment by joshstar** [comment]
A few more little changes before we go stable soon.

- Added `REPEATING` to the MediaListStatus enum (Breaking)
- The Studio media field argument `main` has been renamed to `isMain` (Breaking)
- A bunch of minor bug fixes, including a fix for @zr00130 's issue

**Comment by erengy** [comment]
Hey @joshstar,

I have a couple of questions, although some of them might not be directly related to the API:

- For anime, is `REPEATING` status going to mean `CURRENT` + "rewatching"? From what I can tell, AniList has rewatch counters, but no separate "rewatching" switch like MAL and Kitsu has.

- I'm using raw scores in my application, but having difficulties trying to map values to `POINT_5` and `POINT_3` formats. According to the [APIv1 documentation](https://anilist-api.readthedocs.io/en/latest/lists.html#list-scores), these formats have uneven distributions (29-20-20-20-11 and 30-30-40). Is this intentional? Which exact 100-point values should I use to represent the points in these formats?

- Is `MediaListCollection` guaranteed to return all entries without pagination, even if the user has thousands of them?

- I can't seem to access any seasons before Fall 2013. The API [returns](https://anilist.co/graphiql?variables=%7B%0A%20%20%22season%22%3A%20%22SUMMER%22%2C%0A%20%20%22seasonYear%22%3A%202013%0A%7D&query=query%20(%24season%3A%20MediaSeason!%2C%20%24seasonYear%3A%20Int!)%20%7B%0A%20%20Page%20%7B%0A%20%20%20%20media(season%3A%20%24season%2C%20seasonYear%3A%20%24seasonYear%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20title%20%7Bromaji%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D) an empty array.

- Are media descriptions supposed to contain HTML tags? Cowboy Bebop's description, for example, has a `<br><br>\n`, which I think should just be `\n\n`.

**Comment by joshstar** [comment]
@erengy 

- When a list entry is set to repeating the progress should be reset to 0 and then once they've completed the rewatch the repeat value will be increased by 1. I'll have this all be automatically handled by the server before we go stable.

- By default the score field will return the score formatted to the user's selected score format, you can however provide a `format` argument which will force the score to be returned in the format you want to support, so you won't need to worry about manually converting the score formats on the client then. And you can use the scoreRaw argument on the mediaListEntry mutation instead of the usual score argument and that won't try to unformat the provided score value into the 100 point value we store the scores in in the db.

- Yeah MediaListCollection will return the entire user list, I've tested it on a list with 15k entries which took about 2 seconds to respond, not great but considering most users have no where near that many list items its not much of an issue. 

- Seasons before 2013 - Ah yeah I know why that is, I'll get that fixed.

- Media descriptions are in markdown which does support a subset of html, there are also some descriptions that include a tags. Those and the br tags are mainly a legacy thing though and I would like to go back and convert the descriptions to pure markdown with no html at some point in the near future . You can provide a `asHtml` argument to any markdown field if you'd like to have some more consistency and not worry about the parsing the markdown.

**Comment by erengy** [comment]
Thanks for the explanations.

Regarding raw scores, I'm doing as you said. What I meant is that you should document the mapped values applications should use. I ended up manually extracting these from the website:

`POINT_5`|Raw value|Range
:---:|---:|---:
1|10|1-29
2|30|30-49
3|50|50-69
4|70|70-89
5|90|90-100

`POINT_3`|Raw value|Range
:---:|---:|---:
:(|35|1-35
:&#124;|60|36-60
:)|85|61-100

If applications use different values, it'll cause inconsistencies with the website. Consider the following scenario:

1. User selects `POINT_3` format.
2. User rates *A* with `:|` through the website (raw score is 60).
3. User rates *B* with `:|` through the application (raw score is 36).
4. User selects `POINT_5` format.

Now, *A* has 3-stars while *B* has 2-stars, even though the user rated them the same.

**Comment by joshstar** [comment]
I don't really follow to be honest, your requesting the scores in point_100 but then converting them to the correct score formats on the client? I don't really get why you wouldn't just not force a score format, and let the server auto format the score for you, then you wouldn't need to worry about handling any of this.

The reason I haven't documented that is because ideally a client dev should never need to worry about converting score formats with api v2, they either support all the score formats and let the api server handle the conversions, or force 1 score format and just use that along side scoreRaw. Though thinking about it I guess those ranges should be documented for the point_3 and point_5 so they can convert it correctly for scoreRaw, thought that isn't to likely to be used as most of the time when a client only wants to support a single score format it will be point_10 or point_100.


So I will document those ranges and also note a recommendation for which raw scores to use when using the lower score formats,

**Comment by joshstar** [comment]
The following changes are now live:

- Added SEARCH_MATCH enum to media, character, staff, studio, user, & thread sort enums. 
       -  This gives you more control over how search results are ordered, as previously search_match was the default order when searching and any other provided sort arguments would be a secondary sort. If no arguments are provided when doing a search search_match will still be used as a default.

- Added missing asHtml arguments to remaining markdown fields.

- Media genre_not & tags_not arguments are now exclusive filters instead of inclusive.

- Setting a list item to COMPLETED will automatically set the progress to their max values (if we know them).

- Setting a list item to REPEATING will automatically reset the progress to 0.

- Setting a list item to COMPLETED when it was previously REPEATING will automatically up the repeat counter by 1, and set the progress to their max values (if we know them).

- Attempted to fix filtering pre-2013 media by season returning no values, tho it looks like I've still got some work to do here.

- A bunch a bug fixes and a looot more tests

**Comment by leonekmi** [comment]
When i request this
![image](https://user-images.githubusercontent.com/20224422/32990844-f0824ad8-cd30-11e7-90d8-b40eb57e8985.png)
I got
![image](https://user-images.githubusercontent.com/20224422/32990848-fefda29c-cd30-11e7-8091-fb2b2c5f19a3.png)

with this code : 
```JavaScript
var jsonreq = {
 'grant_type': 'authorization_code',
 'client_id': items.client_id,
 'client_secret': items.client_secret,
 'redirect_uri': "https://leonekmi.twittolabel.fr/anilist-scrobble-altcallback/callback.html",
 'code': c,
};
$.ajax("https://anilist.co/api/v2/oauth/token", {method: "POST", data: JSON.stringify(jsonreq), dataType: "json", complete: function(data) {
 console.log(data);
}});
```

**Comment by joshstar** [comment]
@leonekmi Will take a look a this later today. Though if your doing oauth stuff from client side js you should be using the [implicit grant](https://anilist.gitbooks.io/anilist-apiv2-docs/content/oauth/implicit-grant.html) type as the using auth code grant client sides risks your client secret being stolen.

**Comment by leonekmi** [comment]
@joshstar i found the problem : it was the Content-Type header, you must set it to application/json (same for Accept).

I'm not using implicit because it is an advanced option to set own client id.

**Comment by joshstar** [comment]
@leonekmi Thanks for letting me know, I've updated the oAuth docs with the required headers.

**Comment by joshstar** [comment]
🎉 __Api v2 is now stable!__ 🎉 

You can expect no breaking changes from this point onwards. 

With the stable release of Api v2, Api v1 is now deprecated and will shutdown May 1st 2018. So if you have some apps or services running on v1 now would be a good time to start migrating to v2.

Many thanks for trying out the Api early and providing all the bug reports! 😄
