### ISSUE TITLE
User Favorites are not properly paginated

### ISSUE THREAD

**Issue by danejur** [AniList/ApiV2-GraphQL-Docs#23]
Right now, if I wish to query for a User's Favorites, I can use the following query:
```{
  User {
    favourites(page: 1) {
      anime
    }
  }
}
```
This functions properly, and gives me a subset of the favorites (up to a page limit). However, there is no `PageInfo` entity to either include in the query or receive as a response. This makes effective pagination difficult, as it requires the user to sometimes make an additional request to insure that there are no further pages.
If possible, the `User Favorites` query should allow for additional paging options, and return a `PageInfo` entity to reduce unnecessary traffic and promote uniformity.

**Comment by joshstar** [comment]
Fix for this is now live. 
- pageInfo fields on the different favourite connections should now have their correct values. 
- page and perPage arguments have been added to each favourite connection (anime, characters etc). 
- The page argument on the favourite field on the User type is now deprecated.
