### ISSUE TITLE
Unable to sort mediaList query by title

### ISSUE THREAD

**Issue by ddmgy** [AniList/ApiV2-GraphQL-Docs#24]
While I was reading through the API v2 docs and testing out some queries, I noticed that there is no way to sort mediaList queries by title. The [MediaListSort](https://anilist.github.io/ApiV2-GraphQL-Docs/medialistsort.doc.html) enum does not have any TITLE_* items. However, the [MediaSort](https://anilist.github.io/ApiV2-GraphQL-Docs/mediasort.doc.html) enum has the items TITLE_ROMAJI, TITLE_ENGLISH, TITLE_NATIVE, and *_DESC variants. Obviously, the media and mediaList queries are doing different things, but it seems both should be able to sort by title.

Is there any way to add these (or something similar) to MediaListSort? It seems somehow inconsistent to be unable to sort a user's list by title, when it is available elsewhere in the API.

**Comment by joshstar** [comment]
Generally I do recommend doing sorting on the client as you're likely to need it anyway and its going to be a lot faster than waiting for the entire list request again. 

Currently list performance isn't all that great so I'm not sure if adding a sort by a joining table is going to make that even worse but I'll give it a go and implement it providing it doesn't slow things down too much more.

**Comment by ddmgy** [comment]
I hadn't considered doing the sorting client-side, but now you mention it, that makes a lot of sense. If it ends up being impractical to add, that's fine.

Thank you for the quick response, and for making AniList!
