### ISSUE TITLE
User stats breaking sometimes

### ISSUE THREAD

**Issue by Kazakuri** [AniList/ApiV2-GraphQL-Docs#25]
When querying `favouredGenres` of `UserStats`, the API returns an internal server error when queried from `Viewer` or `MediaListCollection`.

Similarly, `favouredGenresOverview` will return `null` for `meanScore` and `timeWatched` under those conditions.

Both seem to be fine with queried just under `User` though.

**Comment by joshstar** [comment]
This should now be fixed for Viewer and MediaListCollection queries, or any other queries where you can call the user field. 

`favouredGenresOverview` does not supply `meanScore` or `timeWatched` at all, this may be addressed at a later date but will have to wait til after api v1 is shutdown so we can refactor how stats are generated and stored.
