### ISSUE TITLE
500 returned when querying "rankings format" for certain media formats

### ISSUE THREAD

**Issue by danejur** [AniList/ApiV2-GraphQL-Docs#29]
When executing the following query:
```query ($mediaId: Int!) {
  Data: Media(id: $mediaId) {
    rankings {
      format
    }
  }
}
```
with parameters of ```{ "mediaId": 86222 }```
a 500 response code is returned. This appears to be related to the fact that the media in question is a `Manhua`, as opposed to either a basic `Manga` or `Anime`.

**Comment by danejur** [comment]
Sorry for the issue spam. Fat fingered the initial creation.

**Comment by joshstar** [comment]
Thanks, fix for this should be live later tonight.
