### ISSUE TITLE
Syntax error in Page example query

### ISSUE THREAD

**Issue by ricklancee** [AniList/ApiV2-GraphQL-Docs#3]
Because the docs https://joshstar.gitbooks.io/anilist-apiv2-docs/graphql.html are on gitbook i cannot make a PR for them. So here's an issue :) 

There's an error in the example pagination request: 

```
var variables = {
    search: => "Fate/Zero",
    page: 1
};
```

The `=>` causes a syntax error it should be:
```
var variables = {
    search: "Fate/Zero",
    page: 1
};
```

**Comment by joshstar** [comment]
Thanks this should be fixed now, I copied that bit drop the PHP version so guess I missed that.
