### ISSUE TITLE
Custom Lists

### ISSUE THREAD

**Issue by markphilpot** [AniList/ApiV2-GraphQL-Docs#30]
What is the intended way to mange custom lists via the API?  I don't see a mutation to add or remove (for that matter, I don't see a way to remove via the web either).

Also: Might it be possible to add a `customList` argument parameter to MediaList? Otherwise I think  I have to pull the entirety of the media list content in order to render a specific custom list...

One last question: On the `Web -> Anime List -> Theme Editor` there is a section called `List Order` -- is that ordered list stored anywhere that's available from the API? It doesn't seem to match the order that is in `Viewer.mediaListOptions.animeList.customLists`

**Comment by joshstar** [comment]
This is now live :) You can edit custom lists in the UpdateUser mutation.
