### ISSUE TITLE
query.viewer unauthorized?

### ISSUE THREAD

**Issue by MiraiiKuriyama** [AniList/ApiV2-GraphQL-Docs#33]
Hi,

I am trying to get information from the current user. As per document stated I have to use query.viewer:
`query {
  Viewer {
    name
  }
}`

However from my client as well from the [query builder](https://anilist.co/graphiql?query=query%7B%0A%20%20Viewer%20%7B%0A%09%09name%0A%20%20%7D%20%0A%7D) I am getting an Unauthorized message.

`{
  "data": {
    "Viewer": null
  },
  "errors": [
    {
      "message": "Unauthorized.",
      "status": 401,
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}`

I wonder if I am doing something wrong or if this has a reason?

**Comment by Kazakuri** [comment]
Are you sending along an Authorization header with your request?

It won't work in the query builder because it's not setup to be attached to the authenticated user.

**Comment by MiraiiKuriyama** [comment]
It was indeed my authentication, I had:

`
	curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			'Authorization' => 'Bearer ' . $code,
			'Content-Type' => 'application/json',
			'Accept'=> 'application/json',
	));
`

Must be: 
	curl_setopt($ch, CURLOPT_HTTPHEADER, array(
			'Authorization: Bearer ' . $code,
			'Accept: application/json',
	));

And advice for those who are having similar problem that the query is not understood (or being blank), don't set Content-Type to application/json on query requests..

Thanks, you helped me just by saying 

> It won't work in the query builder because it's not setup to be attached to the authenticated user.
