### ISSUE TITLE
Clarification on field nullability

### ISSUE THREAD

**Issue by klanchman** [AniList/ApiV2-GraphQL-Docs#36]
It seems like there are a lot of values throughout the GraphQL schema that are marked nullable, but I'm wondering how accurate some of them are.

Here's an example using an abbreviated version of `MediaListCollection` and some of its children:

```graphql
type MediaListCollection {
  lists: [MediaListGroup]
}

type MediaListGroup {
  entries: [MediaList]
  status: MediaListStatus
}

type MediaList {
  media: Media
}

type Media {
  title: MediaTitle
}

type MediaTitle {
  romaji(stylised: Boolean): String
  english(stylised: Boolean): String
  native(stylised: Boolean): String
  userPreferred: String
}
```

Some things stick out to me in this example, including:
- a `MediaListCollection` may be an array containing `null` elements
- a `MediaList` item's related `Media` may be `null`
- a `Media` item's title may be `null`

I only grabbed parts out of the query that I'm working on currently, but there are other instances throughout the schema that act the same.

Are fields similar to above actually nullable? If not, would it make sense to update the schema to reflect that?

---

**Sidenotes**

I looked over [GraphQL's recommendation](https://graphql.org/learn/best-practices/#nullability) about nullability (they generally prefer things being nullable), and a Facebook developer's [blog post](https://medium.com/@calebmer/when-to-use-graphql-non-null-fields-4059337f6fc8) talking about some pitfalls of non-null fields (a couple comments on that post are good too).

I also looked at some other GraphQL schemas, GitHub's in particular. It has quite a few non-nullable fields, for example the [`PullRequestReview` type](https://developer.github.com/v4/object/pullrequestreview/) has a lot, along with other types. So they might feel differently than Facebook...

The reason I'm asking about this is because I'm writing in Swift, so I'm having to choose between a lot of optional chaining, forced unwrapping, or `guard` statements. It'd be a pain to keep doing it if I don't actually need to worry about some of these things being null 😄

**Comment by joshstar** [comment]
Yeah sorry, honestly the whole field nullability thing got kinda left behind when I was working on the api. 
So there are definitely a lot of fields that will never actually be null (unless theres a network error, or some data corruption) that are set as nullable. However we can't change them now as it would be api-breaking change. 

We'll probably release an api v3 sometime next year, with just a ton of little fixes, nothing big, but correct field nullablity will be a priority then.

As for the fields you listed, the only ones that I can think will ever be null are the english & native titles.

**Comment by joshstar** [comment]
Actually MediaListGroup status would also be null on custom lists.

**Comment by klanchman** [comment]
Thanks for the quick reply!

I think the “network error or data corruption” you mentioned captures Facebook’s / GraphQL’s stance on nullability.

I’d disagree that changing some fields to be non-nullable is a breaking change. Clients that already have null handling for those fields would just never run those handlers, which they shouldn’t anyway if the fields can’t really be null 😉. Going the opposite direction, non-nullable to nullable, _would_ be a breaking change though. 

Good point about custom lists, I haven’t even begun to consider those yet!

Sounds like for now my safest bet is to go by what the schema says. Maybe I’ll make a more convenient representation of the results than what the client I’m using gives me out of the box.

**Comment by joshstar** [comment]
Regarding the breaking change, sometimes you'll reference the type of field or argument in a graphql query or mutation, doing so with an `!` suffix for non-null fields. So if we changed the nullability of fields that would break any queries referencing the type, as the graphql server would expect a ! and return a 400 client error.

**Comment by klanchman** [comment]
Cool, I think I understand 👍 (Still getting the hang of GraphQL)

Thanks for the help!
