### ISSUE TITLE
Include a more verbose query example (javascript)

### ISSUE THREAD

**Issue by ricklancee** [AniList/ApiV2-GraphQL-Docs#4]
```
fetch(url, options).then(handleResponse, handleError);
```

The above line ^ lack a bit of info in the example. People (especially new devs) are going to copy paste the examples and are going to be confused why it's not working. 

I propose to expand the examples a bit. At the least include converting the response to json `response => response.json()` for people not familiar with the fetch api.

Example: 
```
fetch(url, options)
   // Parse the response to json
  .then(response => response.json())
  // Do something with the json response
  .then(response => console.log(response))
  // Handle any errors (invalid request/validation errors)
  .catch(error => console.error(error));
```

Thoughts on this?

**Comment by joshstar** [comment]
Yeah this is a good suggestion. 
Tho I don't really want to fill up to much of the code examples with code that won't be super relevant to the topic of the doc page, so maybe we could define the handleResponse and handleError functions and just include them only in the top example? 

I'd also rather keep the non-node Js examples to ES5 (or at least ES6+ thats already supported in the major browsers), so if people do copy and paste the examples they're not going to need to worry about webpack or browserify.

**Comment by joshstar** [comment]
I've added the gitbook docs to the github repo so feel free to make any pull requests you think are necessary.

**Comment by joshstar** [comment]
Added the functions to the docs, I haven't really used fetch before so there might be a cleaner way to do it still.

**Comment by ricklancee** [comment]
Looks like a solid fetch example, there isn't really a cleaner way of doing things other than using arrow functions, but that's ES6 👍
