### ISSUE TITLE
Media.description(asHtml: false) still contains HTML for some series

### ISSUE THREAD

**Issue by croberts22** [AniList/ApiV2-GraphQL-Docs#40]
When attempting to request media with its description, using the `asHtml` parameter and providing a `false` value can sometimes still return a description with some HTML entities. The most common one I've seen has been `<br>`, but I've also seen some formatters, such as `<i>`.

GraphQL query: https://anilist.co/graphiql?query=query%20Series(%24id%3A%20Int!%2C%20%24type%3A%20MediaType)%20%7B%0A%20%20Media(id%3A%20%24id%2C%20type%3A%20%24type)%20%7B%0A%20%20%20%20id%0A%20%20%20%20idMal%0A%20%20%20%20title%20%7B%0A%20%20%20%20%20%20romaji%0A%20%20%20%20%20%20english%0A%20%20%20%20%20%20native%0A%20%20%20%20%20%20userPreferred%0A%20%20%20%20%7D%0A%20%20%20%20startDate%20%7B%0A%20%20%20%20%20%20year%0A%20%20%20%20%20%20month%0A%20%20%20%20%20%20day%0A%20%20%20%20%7D%0A%20%20%20%20endDate%20%7B%0A%20%20%20%20%20%20year%0A%20%20%20%20%20%20month%0A%20%20%20%20%20%20day%0A%20%20%20%20%7D%0A%20%20%20%20updatedAt%0A%20%20%20%20coverImage%20%7B%0A%20%20%20%20%20%20large%0A%20%20%20%20%20%20medium%0A%20%20%20%20%7D%0A%20%20%20%20description(asHtml%3Afalse)%0A%20%20%7D%0A%7D%0A&variables=%7B%0A%20%20%22id%22%3A%2099423%2C%0A%20%20%22type%22%3A%20%22ANIME%22%0A%7D&operationName=Series

Sample response with id `99423`:

```
"description": "Joint anime project between Trigger and A-1 Pictures's Kouenji Studio (CloverWorks) that was announced at Anime Expo 2017.<br><br>\n\nThe story is set in the distant future. The land is ruined, and humanity establishes the mobile fort city Plantation. Pilots produced inside Plantation live in Mistilteinn, also know as the \"birdcage.\" Children live there knowing nothing of the outside world or the freedom of the sky. Their lives consist of battling to carry out missions. Their enemies are mysterious giant lifeforms known as Kyouryuu, and the children pilot robots called Franxx to face off against them. For the children, riding the Franxx proves their existence.<br><br>\n\nA boy named Hiro is called Code:016, and he was once known as a prodigy. However, he has fallen behind, and his existence seems unnecessary. Not piloting a Franxx is the same as ceasing to exist. One day, a mysterious girl known as \"Zero Two\" appears before him. Two horns grow out of her head.<br><br>\n\n(Source: ANN)"
```

**Comment by Kazakuri** [comment]
From the [Media schema definition](https://anilist.github.io/ApiV2-GraphQL-Docs/media.doc.html):

```gql
# Arguments
# asHtml: Return the string in pre-parsed html instead of
# markdown
```

My understanding is that if `asHtml` is `false` or not provided then markdown will be returned [which is allowed to contain HTML](https://spec.commonmark.org/0.28/#html-blocks) within it.

**Comment by joshstar** [comment]
Yeah Kaz is correct there, isHtml(false) is the same as not including the asHtml argument. I do want to filter the html out of anime/manga descriptions as while it's technically fine to be there it's just not very nice. 

Though it would still be a good idea to support the html sub-set markdown supports if you're planning on supporting any of the community features such as activity or forum comments, as users are free to write html there if they want.

**Comment by croberts22** [comment]
Ah gotcha, I think I was misinterpreting the description then! Yeah, it'd be nice to have a separate option to filter out any formatters in the event you just wanted the raw text.
