### ISSUE TITLE
How to create a new message on the feed?

### ISSUE THREAD

**Issue by Ghor3d** [AniList/ApiV2-GraphQL-Docs#41]
I can't seem to understand how uploading a message works, I've also tried looking at other issues but I didn't find the answer.Can someone point out an example please?

**Comment by joshstar** [comment]
Sorry for the late reply, here's an example mutation for message creation:
```
mutation ($recipientId: Int, $text: String) {
    SaveMessageActivity(recipientId: $recipientId, message: $text) {
        id
        type
        message
        replyCount
        createdAt
        messenger {
            name
            avatar {
                large
            }
        }
    }
}
```

Mutations docs and more examples are available [here](https://anilist.gitbooks.io/anilist-apiv2-docs/graphql/mutations.html). You'll need to use oAuth to authenticate as a user to send it too, docs for that are [here](https://anilist.gitbooks.io/anilist-apiv2-docs/oauth.html)

**Comment by Ghor3d** [comment]
Thank you.
