### ISSUE TITLE
Standard Markdown

### ISSUE THREAD

**Issue by lionirdeadman** [AniList/ApiV2-GraphQL-Docs#43]
Anilist should give out Markdown instead of HTML for a lot of things such Activities, About descriptions,

## Why?

1. Standardization : This standard can be read by a lot of people without trying to decipher it.
2. Performance : Markdown doesn't require a webview or anything of the like to be rendered properly unlike HTML/CSS which means it makes performance better which is especially important for mobile apps.
3. Usability : The user doesn't need to learn how Anilist does styling if it's using Markdown because a lot of other services use it so it's more likely that the user knows how to do it.

**Comment by joshstar** [comment]
At this point, I think we have far too much user data built on our markdown so I don't think this would be a sensible change to enforce on users really. Markdown does also support a subset of HTML. 

One of the main reasons we have some custom markdown tags is entirely for usability, for example I don't think the default image embed markdown (`![alt text](url)`) is all that user friendly or clear compared to `img(url)`. Requiring multiple line breaks is also a pain point for new users of markdown, even github dosen't bother with those. Finally it would also limiit a lot of the additional functionaility the site has been built around, like youtube embeds and spoilers.

If api devs don't want to support those extra markdown features that isn't a problem at all, and I like to think most of our custom tags are simple enough that they could be easiliy filiterd out with some basic regex if need be.
