### ISSUE TITLE
Requesting studios in mutation returns Internal Server Error

### ISSUE THREAD

**Issue by erengy** [AniList/ApiV2-GraphQL-Docs#45]
[This query](https://anilist.co/graphiql?query=query%20(%24id%3A%20Int!)%20%7B%0A%20%20Media%20(id%3A%20%24id%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20id%0A%20%20%20%20title%20%7B%20romaji%20%7D%0A%20%20%20%20studios%20%7B%20edges%20%7B%20node%20%7B%20name%20%7D%20%7D%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22id%22%3A%204087%0A%7D) works as expected:

```gql
query ($id: Int!) {
  Media (id: $id, type: ANIME) {
    id
    title { romaji }
    studios { edges { node { name } } }
  }
}
```

[This mutation](https://anilist.co/graphiql?query=mutation%20(%24id%3A%20Int%2C%20%24mediaId%3A%20Int%2C%20%24progress%3A%20Int)%20%7B%0A%20%20SaveMediaListEntry%20(id%3A%20%24id%2C%20mediaId%3A%20%24mediaId%2C%20progress%3A%20%24progress)%20%7B%0A%20%20%20%20id%0A%20%20%20%20progress%0A%20%20%20%20media%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20title%20%7B%20romaji%20%7D%0A%20%20%20%20%20%20studios%20%7B%20edges%20%7B%20node%20%7B%20name%20%7D%20%7D%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&variables=%7B%0A%20%20%22id%22%3A%2036900038%2C%0A%20%20%22mediaId%22%3A%204087%2C%0A%20%20%22progress%22%3A%2015%0A%7D) (with authorization) returns Internal Server Error, even though AniList updates user's list:

```gql
mutation ($id: Int, $mediaId: Int, $progress: Int) {
  SaveMediaListEntry (id: $id, mediaId: $mediaId, progress: $progress) {
    id
    progress
    media {
      id
      title { romaji }
      studios { edges { node { name } } }
    }
  }
}
```

Removing `studios { edges { node { name } } }` from the mutation solves the issue.

**Comment by joshstar** [comment]
Sorry for the delay! Was away from home for the past couple weeks, fix for this should be live now.
