### ISSUE TITLE
Resetting Notification Count

### ISSUE THREAD

**Issue by HiruNya** [AniList/ApiV2-GraphQL-Docs#46]
How can I make it so that the unread notifications I query are set to read so that they won't appear next time I query the notifications?
My current query is this and I assumed that the above could be done if I set ``resetNotificationCount`` to ``true`` however it seems to not affect the result at all as I get the same notifications back every time.
```graphql
query ($page_num: Int, $reset_notification: Boolean) {
  Page(page: $page_num) {
    pageInfo {
      currentPage
      hasNextPage
    }
    notifications(type: AIRING, resetNotificationCount: $reset_notification) {
      ... on AiringNotification {
        id
        media {
          id
          title {
            romaji
          }
          status
          coverImage {
            large
          }
          siteUrl
        }
      }
    }
  }
}
```
The variables I give in are:
```json
{
  "page_num": 1,
  "reset_notification": true
}
```
And the result is that every time I send this I get the same two notifications back.
Is there another type of query I need to use?
The workaround I use is to record the id of the first notification so that the next time I read it I can read all the notifications until I encounter the id of the notification I had recorded before.

**Comment by joshstar** [comment]
The notification query provides all notifications regardless of whether they've been read or not. You can use the `unreadNotificationCount` to work out which ones you want to display on your client.

In the future I would like to support something like this but probably won't be all too soon.

**Comment by HiruNya** [comment]
Ah I see, that makes much more sense!
Thank you for the help.
