### ISSUE TITLE
Get current chapter/volume for an ongoing manga

### ISSUE THREAD

**Issue by Der-Eddy** [AniList/ApiV2-GraphQL-Docs#47]
I know how to get the last aired episode for animes
```
{
  Media(search: "Steins;Gate 0", type: ANIME) {
    title {
      romaji
      english
    }
    nextAiringEpisode {
      episode
    }
  }
}
```
`['Media']['nextAiringsEpisode']['episode' ]` minus one would result in the last aired episode for the stated example Steins;Gate 0

however, the same would only yield `null` for manga queries like
```
{
  Media(search: "Boku no hero academia", type: MANGA) {
    title {
      romaji
      english
    }
    chapters
    volumes
    nextAiringEpisode {
      episode
    }
  }
}
```

and `chapters` and `volumes` yield also only `null` since they only state the amount when complete

is there no way to get the last published chapter/volumes from an ongoing manga? Or do I miss something?

**Comment by joshstar** [comment]
We don't currently support chapter/volume counts for currently publishing manga or really have any plans to do so. 

Manga releases can be a lot more sporadic than anime and there are many multiples more currently publishing manga compared to airing anime, it's just not something we could practically support at a good enough standard to be reliable. Sorry.
