### ISSUE TITLE
ListScoreStats.meanScore returns null. No documentation stating null is a possible value

### ISSUE THREAD

**Issue by trigger-death** [AniList/ApiV2-GraphQL-Docs#51]
When AniList is missing a mean score that would appear on the user's overview page, the resulting value in json is returned as `null`.

* The first issue is that the mean score wasn't present when multiple manga were scored.
* The biggest issue is that nobody is expecting `null` from a type `Int` with no comments attached.

**Comment by joshstar** [comment]
The mean score may be null if we haven't yet calculated the value, that job is set to run every 24 hours so its likely for new users, or for users without any scored manga.

In Graphql all types are nullable by default, a non-null type is denoted with a `!` suffix. Our docs are generated off of our code, and neither of the fields in [ListScoreStats](https://anilist.github.io/ApiV2-GraphQL-Docs/listscorestats.doc.html) are non-null. If we provide a null value to a non-null field it will acutally result in a server type error so there shoulnd't be anywhere where we're returning a null value for a non-nullable field.

Hope that clears things up.

**Comment by trigger-death** [comment]
Ah, thank you. My apologies for being new to GraphQL and not aware of this fact.
