### ISSUE TITLE
Need little help

### ISSUE THREAD

**Issue by BenisBudder** [AniList/ApiV2-GraphQL-Docs#53]
Ill try currently to filter in my request the Media_Format, like I wanna just see the "TV"-Format. Not the e.g. "Specials".

Tried something of these but it wont work for me:

```
var variables = {
    search: anime,
    format: 'TV',
    format_in: 'TV'
  };
```

Tested it on "Black Clover" (the input) and get the "Black Clover: Jump Festa 2016 Special" back instead of just the TV Serie Black Clover.

**Comment by joshstar** [comment]
Hmm this query:

```
query ($search: String) {
  Page {
    media (type: ANIME, search: $search, format: TV) {
 	  id
      title {
        romaji
      }
    }
  }
}
```

With "black clover" as the search var returns the correct response, so not sure whats wrong with your query without seeing it.

**Comment by BenisBudder** [comment]
Thx, im just dunb,
Forgett to set the "fromat" - filter in the header ...
