### ISSUE TITLE
how to use api for client apps

### ISSUE THREAD

**Issue by ahmed56734** [AniList/ApiV2-GraphQL-Docs#54]
where are the endpoints I should  to request the data !

**Comment by alex-mac** [comment]
@ahmed56734 

https://anilist.gitbook.io/anilist-apiv2-docs/overview/graphql/getting-started

There are instructions on using the API here. You can download a tool like [Altair GraphQL Client](https://altair.sirmuel.design/#download) to test graphQL endpoints.

Here is a screenshot of the endpoint in action with the results back:

<img width="1282" alt="screen shot 2018-10-27 at 9 00 12 am" src="https://user-images.githubusercontent.com/14145199/47606301-e562a780-d9c6-11e8-95a0-c5965d83996c.png">

Happy Building :)

**Comment by ahmed56734** [comment]
@alex-mac I thought it would be normal get and post requests with a specified json response :confused:
now I have to learn about graphql to use the api in my android app :worried:
