### ISSUE TITLE
Can't get `X-RateLimit-Remaining` and other response headers

### ISSUE THREAD

**Issue by andrew1007** [AniList/ApiV2-GraphQL-Docs#57]
It's included in the response, because I can see it in the network activity, but I don't have access to it from the response. Running this in the chrome dev console on an empty tab will show the available headers. This dummy request will `400`, but I should technically still have access to the headers.

``` javascript
const request = async () => {
    const url = 'https://graphql.anilist.co'
    const header = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
        },
        body: JSON.stringify({
            query: '',
        }),
        mode: 'cors'
    }
    try {
        const response = await fetch(url, header)
        response.headers.forEach((k, v) => { console.log(k, v) })
        // console.log output:
        // no-cache, private cache-control
        // application/json content-type
        const json = await response.json()
        if (response.ok) {
            return json
        } else {
            return Promise.reject(json)
        }
    } catch (error) {
        throw error
    }
}

request()
```

**Comment by joshstar** [comment]
Ah sorry think this is due to some changes I made recently, must have messed something up. 

Testing your request now (after a fresh options so the browser can refresh the headers) the x-ratelimit headers are showing in the response.

**Comment by andrew1007** [comment]
Sorry to be such a bother, but I still don't see it :(. Tried it with a hard refresh and in incognito. Am I doing something wrong here? Am I supposed to have certain permissions set up?

<img width="1143" alt="screen shot 2018-12-21 at 9 30 03 am" src="https://user-images.githubusercontent.com/16946474/50355343-38f2fc80-0503-11e9-8af2-2836932a1d7b.png">

**Comment by joshstar** [comment]
Ah okay it looks like we don't send those headers back on 400 response, try making your query string `{User(id: 1) {id}}` for testing purposes to see if that works

**Comment by andrew1007** [comment]
Excellent! I see them in my response headers. Thanks a bunch

**Comment by andrew1007** [comment]
Hello again! Headers seem to be missing again :(
