### ISSUE TITLE
Queries using Page return a 400 error

### ISSUE THREAD

**Issue by bvalyan** [AniList/ApiV2-GraphQL-Docs#7]
I'm using Apollo-Android to migrate to the v2 API and most of my queries are working. However, whenever I try to retrieve pages I just get a 400 error. I've tested the query in the builder and it works fine, but I only get a 400 response from the app. This is my query

```
query AllAnime{
                Page{
                media(isAdult: false, status: RELEASING, type: ANIME) {
                  id
                  episodes
                  startDate {
                    day
                    month
                    year
                  }
                  endDate {
                    day
                    month
                    year
                  }
                  title {
                    english
                  }
                  coverImage {
                    large
                  }
                  genres
                  popularity
                  description
                	}
                }
              }
```
If I just use Media for one anime the query works fine, but as soon as I put in page I get the error.

**Comment by joshstar** [comment]
Yeah the query works fine in graphiql so the issue is probably to do with how your sending the request and not the query it self.
The 400 response should contain some information about what the issue is, other than that I can't really help unless you want to provide some more details, like the code used for making the request.

**Comment by bvalyan** [comment]
Fair enough. The response's message field was actually blank, so that didn't tell me much. I am using Okhttp with Apollo in Android. 

Here's some request info

`Request{method=POST, url=https://graphql.anilist.co/, tag=null}`

`{"query":"query AllAnime {  Page {    __typename    media(isAdult: false, status: RELEASING, type: ANIME) {      __typename      id      episodes      startDate {        __typename        day        month        year      }      endDate {        __typename        day        month        year      }      title {        __typename        english      }      coverImage {        __typename        large      }      genres      popularity      description    }  }}","variables":{}}`

content type
`application/json; charset=utf-8`

**Comment by joshstar** [comment]
Looks like the top level __typename in the Page query was causing an error, just pushed a fixed for that so let me know if thats fixed it or if its something else still.

**Comment by bvalyan** [comment]
Working like a charm. You're the man! Thanks for the quick help.

**Comment by bvalyan** [comment]
Oh one question. The request is returning now but the format doesn't look like JSON. is this something on my end or something with how Graphql works? This is my first time using it. This is part of my response

`Data{Page=Page{__typename=Page, media=[Medium{__typename=Media, id=21, episodes=null, startDate=StartDate{__typename=FuzzyDate, day=20, month=10, year=1999}, endDate=EndDate{__typename=FuzzyDate, day=null, month=null, year=null}, title=Title{__typename=MediaTitle, english=null}, coverImage=CoverImage{__typename=MediaCoverImage, large=https://cdn.anilist.co/img/dir/anime/reg/21.jpg}, genres=[Action, Adventure, Comedy, Drama, Fantasy], popularity=12813, description=Gol D. Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by the World Government brought a change throughout the world. His last words before his death revealed the location of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece (which promises an unlimited amount of riches and fame), and quite possibly the most coveted of titles for the person who found it, the title of the Pirate King.<br><br>
Enter Monkey D. Luffy, a 17-year-old boy that defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate who ransacks villages for fun, Luffy’s reason for being a pirate is one of pure wonder; the thought of an exciting adventure and meeting new and intriguing people, along with finding One Piece, are his reasons of becoming a pirate. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach One Piece.<br><br>

**Comment by joshstar** [comment]
Hmm I honestly have no idea, the Api can only return Json so I have to guess thats something Apollo android is doing?

**Comment by bvalyan** [comment]
Maybe, I'll keep looking into it.

**Comment by bvalyan** [comment]
In case anyone else uses this API on Android, turns out the Apollo converts the JSON to its own data type behind the scenes. I had to make an interceptor for the request to get the raw JSON back, but I'm good now!
