### ISSUE TITLE
'Viewer' object is absent in schema documentation 

### ISSUE THREAD

**Issue by IAmVisco** [AniList/ApiV2-GraphQL-Docs#72]
I had troubles getting currently authenticated user so I went to check how it's done on the site itself. Turns out it fetches for 'Viewer' object that is completely missing from [the schema documentation](https://anilist.github.io/ApiV2-GraphQL-Docs/). Not sure if that's intentional or just a mistake.

**Comment by joshstar** [comment]
Viewer isn't an object but a query that returns the User object. So Viewer is on the query page of the schema docs and not included in the sidebar under Object.

I'm not really a big fan of the schema docs generator we're using currently as it dumps all the queries onto one big page which makes them hard to find. Will hopefully switch to a better alternative soon.
