### ISSUE TITLE
Is the server down? (500 Internal Server Error)

### ISSUE THREAD

**Issue by keldenl** [AniList/ApiV2-GraphQL-Docs#79]
Seems like the server is down? Doesn't work in my app or the online interactive graphql query editor (https://anilist.co/graphiql).

The server was working up until around 3 or 4 hours ago?

**Comment by keldenl** [comment]
UPDATE: Some of my queries work and some do not

This DOESN'T WORK
```
{
    Page (page: 1, perPage: 5) {
    pageInfo {
      total
      currentPage
      lastPage
      hasNextPage
      perPage
    }
    characters (search: "naruto") {
      id
      name { full }
      image { medium }
      media (sort: POPULARITY_DESC, page: 1, perPage: 1, type: ANIME) {
        nodes {
          title { romaji }
          seasonYear
        }
      }
    }
  }
}
```

But this query DOES work:
```
{
  Staff (id: 95015) {
    characters (page: 1, perPage: 20) {
      pageInfo {
        currentPage
        lastPage
        hasNextPage
      }
      edges {
        node {
          name { first last }
          image { medium }
        }
        role
        media {
          title { romaji }
          popularity
        }
      }
      
    }
  }
}
```

Both of these have been run in the online GraphQL editor and locally. The first example query worked up until earlier today but without changing any code (ran the same code that worked previously, as well as checked my unchanged deployed code) it now no longer works. 

I'm not sure what the issue is or how to solve it :(

**Comment by RakSrinaNa** [comment]
What seem to not work is using `characters` with the `search` parameter. Using it with no parameters or with an ID does work.

**Comment by keldenl** [comment]
Just tried it again and everything seems to be working as expected again! @RakSrinaNa the `search` parameter now works again! 😀
