### ISSUE TITLE
Language argument not working on voiceActors

### ISSUE THREAD

**Issue by soruly** [AniList/ApiV2-GraphQL-Docs#8]
I think this query is supposed to only return a list of voice actors whose language is japanese
But it is now returning voiceActors of all languages instead
```
{
  Media(id: 1, type: ANIME) {
    id
    title {
      native
      romaji
      english
    }
    characters {
      edges {
        node {
          id
          name {
            native
          }
        }
        role
        voiceActors(language: JAPANESE) {
          id
          name {
            first
            last
            native
          }
          language
        }
      }
    }
  }
}
```

[Link on GraphiQL](https://anilist.co/graphiql?query=%7B%0A%20%20Media(id%3A%201%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20id%0A%20%20%20%20title%20%7B%0A%20%20%20%20%20%20native%0A%20%20%20%20%20%20romaji%0A%20%20%20%20%20%20english%0A%20%20%20%20%7D%0A%20%20%20%20characters%20%7B%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20native%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20role%0A%20%20%20%20%20%20%20%20voiceActors(language%3A%20JAPANESE)%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20first%0A%20%20%20%20%20%20%20%20%20%20%20%20last%0A%20%20%20%20%20%20%20%20%20%20%20%20native%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20language%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

**Comment by joshstar** [comment]
Thanks, can confirm the issue tho I can't seem to replicate it locally 😞 so might take a little while to fix.

**Comment by joshstar** [comment]
Fix is now live 😄
