### ISSUE TITLE
Incorrect anime for idMal

### ISSUE THREAD

**Issue by Aimiks** [AniList/ApiV2-GraphQL-Docs#81]
Vinland Saga id on MAL : 37521
Searching with  "Media(idMal : 37521)" should return "Vinland Saga" but return "Seto no Omise no Okyakusama" that have 37521 in idMal.

How do you put your idMal, is it manual from mods or is it some sort of automatization things ?

**Comment by RakSrinaNa** [comment]
The result is correct. "Seto no Omise no Okyakusama" have the same id in MAL but is a different type (manga vs anime). You probably want to use `Media(idMal: 37521, type: ANIME)` instead or use a paged query to get both:
```
query{
  Page(page: 1, perPage: 5){
    pageInfo{
      currentPage
      hasNextPage
    }
    media(idMal: 37521){
      id
      idMal
      title{
        romaji
      }
      type
    }
  }
}
```

**Comment by Aimiks** [comment]
Oh you're right, totally my bad here. Thanks for the help @RakSrinaNa
