### ISSUE TITLE
Update user list item by mal id

### ISSUE THREAD

**Issue by Teranode** [AniList/ApiV2-GraphQL-Docs#83]
Would it be possible to specify the idMal field when a user is updating their listing in the api.
Reason being that most people have their base set up to work with MAL by default. If updating a user's anime list via Anilist's api and then idMal is there, then someone can create a field in their own database connecting Anili's Id to their own database by finding what MAL Id connects.

**Comment by joshstar** [comment]
No plans for this sorry. I think a similar result could be achieved with a little more work just using the malId from the media object itself.
