### ISSUE TITLE
Transport-Level Batching not possible

### ISSUE THREAD

**Issue by Peatral** [AniList/ApiV2-GraphQL-Docs#84]
I have the problem that I need to find a list of ids with the ids of mal. To not stress the server or something like that I try to send as few requests as possible and in that specific case where I would need one request per anime i need to check batching would be useful.
I can't use query merging because if one fails (eg. bc the anime is not listed on anilist) everything fails as mentioned in #52. Transport level batching should solve the problem because the queries get handled individually while still needing just one request. [Here](https://blog.apollographql.com/query-batching-in-apollo-63acfd859862) more.
If you look [here](https://github.com/wp-graphql/wp-graphql/issues/653#issuecomment-454099419) you can see a working example of it, just try:
When you try something like this with the anilist api you will get an error.
<pre>fetch( 'https://graphql.anilist.co', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify([
    { 
      "query": 'query AnimeByMalIDQuery {Media (idMal: 1, type: ANIME) {id title {romaji}}}',
      "operationName": 'AnimeByMalIDQuery'
    }, 
    { 
      "query": 'query AnimeByMalIDQuery {Media (idMal: 5, type: ANIME) {id title {romaji}}}',
      "operationName": 'AnimeByMalIDQuery'
    }
  ]),
})
.then( res => res.json() )
.then( console.log );</pre>
You will get the error 

> No query or mutation provided. Please view https:/…/graphiql to see available queries and mutations.

I'm still new to graphql and this seems like the right solution for me, so I'm not sure how to handle this situation without transport level batching, query merging or sending a lot of requests .

**Comment by Kazakuri** [comment]
One thing that might be worth investigating would be a single query in the `Page` type and using `media(idMal_in: [1, 5])`.

You'd have to request the `idMal` field in the response and could then match the responses to the IDs on the client side

**Comment by joshstar** [comment]
Query batching is a feature of Apollo only and not normal graphql, so no plans to implement it. It would require the same fix as #52 to work correctly in this instance anyway.

As @Kazakuri said, a paged query with idMal_in should provide you the results you're looking.

**Comment by Peatral** [comment]
That looks actually really promising, though I'm not quite sure how to interpret the testing responses.
Trying this 
<pre>fetch( 'https://graphql.anilist.co', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
	"user-agent": "JS GraphQL"
  },
  body: JSON.stringify(
    { 
      "query": 'query AnimeByMalIDQuery {Page (page: 1) {pageInfo {total currentPage lastPage hasNextPage perPage} media (idMal_in: [1, 5]) {id idMal title {romaji}}}}',
      "operationName": 'AnimeByMalIDQuery'
    }),
})
.then( res => res.json() )
.then( console.log );</pre>
will result in a response with 3 Medias where Monster seemingly also has an idMal of 1.
Doing the same thing with id that don't exist on anime list eg. [1,2,3,4,5] (only 1 and 5 are given, both on mal and anilist but that shouldn' actually matter), you will get confusing results.
But the ids should actually be the same for the lower digits so I think this is a case that shouldn't actually be happing.
To make it short - it's a good workaround that should be pretty solid and should work in most of the cases.

**Comment by Kazakuri** [comment]
Ah, add `type: ANIME` to the query. Monster is ID 1 on MAL for manga.

**Comment by Peatral** [comment]
Oh lol thanks, I didn't look the ids of the mangas up.
