### ISSUE TITLE
Not receiving an access_token when using the implicit grant

### ISSUE THREAD

**Issue by MattIzSpooky** [AniList/ApiV2-GraphQL-Docs#85]
I followed the docs and my callback is being called. The problem is that the callback is being called without the `access_token`.

The callback URL is set as it should be.
![image](https://user-images.githubusercontent.com/26460447/75801286-2a48dc00-5d7b-11ea-8bc6-757b53d3fa4c.png)

Here is the code.
```ts
const BrowserWindow = electron.remote.BrowserWindow;
let authWindow: electron.BrowserWindow | null = new BrowserWindow({
  width: 800,
  height: 600,
  show: false,
  webPreferences: { nodeIntegration: false }
});

http.createServer((req, res) => {
  console.log(url.parse(req.url!));
  res.end("Success");
}).listen(8000);

authWindow.loadURL(`https://anilist.co/api/v2/oauth/authorize?client_id=<CLIENT_ID>&response_type=token`);

authWindow.show();
```

Here is the result.
![image](https://user-images.githubusercontent.com/26460447/75801189-038aa580-5d7b-11ea-9ea7-c025665df347.png)

Does anyone have an idea what I might be doing wrong?
Is it possible that `localhost` is not supported?

**Comment by Kazakuri** [comment]
Hm, localhost should definitely be supported. If you open the window in a proper web browser does the access token show in the URL bar after the redirect?

**Comment by MattIzSpooky** [comment]
> Hm, localhost should definitely be supported. If you open the window in a proper web browser does the access token show in the URL bar after the redirect?

Yes, that seems to work somehow, but now I wonder why everything after the `#` is seen as invalid invalid or something.

It could be that the Node HTTP server automatically removes everything after the `#` character.

**Comment by MattIzSpooky** [comment]
I think I found out what the problem is. @Kazakuri 

https://stackoverflow.com/questions/9967681/nodejs-url-with-hash

This really sucks :/

**Comment by MattIzSpooky** [comment]
Guess I'll use the [Auth PIN](https://anilist.gitbook.io/anilist-apiv2-docs/overview/oauth/getting-started#auth-pin) method and write some code to remove the required user interaction when using this method.

**Comment by MattIzSpooky** [comment]
I felt like I have to leave something behind because I figured out how to get it to work.
So here's how to get an `access_token` using the [Auth PIN](https://anilist.gitbook.io/anilist-apiv2-docs/overview/oauth/getting-started#auth-pin) that requires minimal user interaction.

This is a snippet of how my code looks like right now. Its probably not the best but it works. I just want to help those who run into something like this in the future.

```ts
import electron from 'electron';

export class Anilist {
  login() {
    const BrowserWindow = electron.remote.BrowserWindow;

    let authWindow: electron.BrowserWindow | null = new BrowserWindow({
      width: 800,
      height: 600,
      modal: true,
      parent: electron.remote.getCurrentWindow(),
      show: false,
    });
    authWindow.webContents.on('dom-ready', () => {
      if (!authWindow) {
        return;
      }

      const url = authWindow.webContents.getURL();

      if (url.includes("pin")) {
        authWindow.close();
        this.parseToken(url);
      }
    });

    authWindow.loadURL(`https://anilist.co/api/v2/oauth/authorize?client_id=<CLIENT_ID>&response_type=token`);

    authWindow.show();

    authWindow.on('closed', () => {
      authWindow = null;
    });
  }

  private parseToken(urlWithToken?: string) {
    if (!urlWithToken) {
      throw new Error('Something went wrong'); // TODO: improve message
    }

    console.log(this.extractTokenFromUrl(urlWithToken))
  }

  private extractTokenFromUrl(urlWithToken: string): string {
    const result = /(?<=access_token=).+?(?=&)/.exec(urlWithToken);

    if (!result) {
      throw new Error('Could extract token from url.');
    }

    return result[0];
  }
}
```
