### ISSUE TITLE
Need help to get a random character

### ISSUE THREAD

**Issue by paolokhai** [AniList/ApiV2-GraphQL-Docs#87]
Hi i'm making a project to generate a random character and i wanted to get only a character with 50 more favourites. I couldn't find any interface to help me, am i missing something?

Right now I'm getting the number of characters N and generating a character with a random ID between 1 and N

**Comment by paolokhai** [comment]
I mean, asking it until i'm able to find one is kind of stupid and will fill my server requests

**Comment by Kazakuri** [comment]
You could use a `Page` with `perPage: 1` and use the generated number as the page number.

**Comment by paolokhai** [comment]
And I would get from 1 to 50 characters, but they would still be random and the favorites wouldn't be filtered right? There is no way to filter them?

Because the code is working fine but I get random characters with 0 favorites that no one knows and I'd like to be able to filter them

**Comment by Kazakuri** [comment]
Ah, I read your comment as only the 404 being an issue, I didn't realize there weren't that many filter options on the character request.

Without that filter being added your best bet would be using `sort: [FAVOURITES_DESC]` to find the number of characters with more than 50 favourites (binary search). 
Then you could generate a number in that range and doing the same `page: $randomNumber, perPage: 1` query with `sort: [FAVOURITES_DESC]` on the character field to get the random character.

The page check could be cached with fairly low risk, but even then querying for that should only be 5-10 requests.

**Comment by paolokhai** [comment]
Trying with pages i can get what i want in a really low number of requests, and it's not something i will do very often so i guess I'm okay for now
