### ISSUE TITLE
Get anime/mangalist of authenticated user (or somebody else who has public anime/mangalist)

### ISSUE THREAD

**Issue by leonekmi** [AniList/ApiV2-GraphQL-Docs#9]
The onList bool of Media object should be better and includes progress and score.
(and create a new query obj. to do like in the APIv1)

**Comment by joshstar** [comment]
You can use the `mediaListEntry` field on the media object to get the authenticated user's list data for that media.

If you want the entire list of a user you should use the `MediaList` field within the `Page` query or just the `MediaListCollection` query if you want the entire list pre-grouped into sections.

**Comment by leonekmi** [comment]
the mediaListEntry returns null :/
mediaListEntry {
 status
 progress
}
(in a media query)
![screen](https://i.imgur.com/QJWR5om.png)
![screen 2](https://i.imgur.com/puKRYrD.png)

**Comment by joshstar** [comment]
Sorry about that, just pushed a fixed for it so mediaListEntry should return the correct values now.
MediaListEntry is doced on the Media type [here](https://anilist.github.io/ApiV2-GraphQL-Docs/media.doc.html).

**Comment by leonekmi** [comment]
Thanks for the details and the fast answer !

also look at my second edit !

**Comment by joshstar** [comment]
Query names are UpperCamelCase while field are camelCase, as mediaList list is a field on the Page query it should be camelCase so you want a lower case m:
```
{
  Page {
    mediaList {
      id
    }
  }
}
```
