### ISSUE TITLE
Apollo Client :  SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by Alfrex92** [AniList/ApiV2-GraphQL-Docs#91]
Hi, I'm trying to use React + Apollo client with AniList API, but I have the following error:

```  SyntaxError: Unexpected end of input ```

Here is my code:

https://codesandbox.io/s/anilist-api-apollo-dqxo3?file=/src/App.js

And you can see the error here:

https://dqxo3.csb.app/

Any idea of how can I fix it?

Thanks!

**Comment by Alfrex92** [comment]
any idea?

**Comment by system32uwu** [comment]
You may want to close this since your example is working correctly
