### ISSUE TITLE
[Feature Request] Add support for Synonyms in search for API

### ISSUE THREAD

**Issue by joseph619** [AniList/ApiV2-GraphQL-Docs#93]
Usually for Manhua and Manhwa, the names are always in unofficial English on most manga sites, and they don't use Romaji. 

For example, Volcanic Age is the commonly used name for Hwasanjeonsaeng on Manga sites, so most people search for the Synonym instead of the romaji or English name (most English names are null for Manhua and Manhwa). This results in broken search.

For users to identify the title easily, please add search for Synonyms in API, thank you.

**Comment by joshstar** [comment]
Search already accounts for synonyms, it's just not very accurate and difficult to get working well across all our media and title types. I'll have another go soon improving result accuracy but I can't promise that will just work perfectly.
