### ISSUE TITLE
Episode Info?

### ISSUE THREAD

**Issue by da3dsoul** [AniList/ApiV2-GraphQL-Docs#96]
For AniChart to work, I'd assume that date info for every episode exists, with rather specific times, at that.
The only Episode info I could find in the API was StreamingEpisodes, which returns some useful info, but I could see it being fairly empty if Crunchyroll or Funimation (or some other legit streaming platform) doesn't have it online.

For my cross reference generator, I need (really want) a date to go with the title of the episode, and episode numbering returned in an int separate from the title would give a more reliable model for parsing. No idea if AniList even bothers keeping an episode number, as specials, OVAs, etc love to make numbering difficult. If that's the case, then some kind of key that guarantees unique identification would work.

What I would expect of an episode model from the data that AniList appears to have:
```
Episode
{
  Title: string
  EpisodeNumber: int
  DateAired: ISO8601 Datestring // possibly have more than one, depending on if there's data for different regions/sources
  link to anilist discussion thread for the episode
  ratings
  watch links
  thumb
// Not sure if this is actually there, but would be nice
  Description/Synopsis
```

**Comment by da3dsoul** [comment]
So Airing Schedule would theoretically solve this, as that's what AniChart runs on, but querying that by MediaId only returns one episode...and it's the first one, which aired 11 weeks ago... Is it my query? Everything I could find says that that should be correct
```
query {
  AiringSchedule(mediaId: 108632) {
    id,
    airingAt,
    timeUntilAiring,
    episode,
    media {
      title {
        romaji
        english
        native
        userPreferred
      }
    }
  }
}
```

**Comment by QikLiang** [comment]
@da3dsoul Hey, if you still haven't figured it out yet, you need to put it in a page:
```
query{
  Page(page:1 perPage:50){
    airingSchedules(mediaId: 108632) {
      id,
      airingAt,
      timeUntilAiring,
      episode,
      media {
        title {
          romaji
          english
          native
          userPreferred
        }
      }
    }
  }
}
```

**Comment by da3dsoul** [comment]
Thank you

**Comment by maisans-maid** [comment]
> So Airing Schedule would theoretically solve this, as that's what AniChart runs on, but querying that by MediaId only returns one episode...and it's the first one, which aired 11 weeks ago... Is it my query? Everything I could find says that that should be correct
> 
> ```
> query {
>   AiringSchedule(mediaId: 108632) {
>     id,
>     airingAt,
>     timeUntilAiring,
>     episode,
>     media {
>       title {
>         romaji
>         english
>         native
>         userPreferred
>       }
>     }
>   }
> }
> ```

idk if you have figured it out yet but you need to use `nextAiringEpisode` instead of `episode`.
